# Generated by Django 3.2.9 on 2021-11-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='User name')),
                ('message', models.CharField(max_length=5, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='StatInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Count connected')),
            ],
        ),
    ]
